layout_spectrum: 0.15548754902556539
typography_spectrum: 0.6087468648329377
color:
  brandStrength: 0.9450905059929937
  lightness: 0.8978571079205722
  saturation: 0.3585983538068831
  rhythmicContrast: 0.7473579186480492
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9087c70a-42f4-4b63-a7bb-9f5ea17937a9.jpg
  type: website
author:
  name: Jeffrey Lain
  email: sinotai@gmail.com
name: 'Ultimate Aussie Trip '
title: Jeffrey's Testing!
