typography_spectrum: 0.7665383075363934
color:
  brandStrength: 0.5608424402307719
  lightness: 0.09823664324358106
  saturation: 0.35089389397762716
  rhythmicContrast: 0.5937971943058074
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d39eaf1f-3602-48af-aeb8-17e0d4292775.jpg
  type: website
layout_spectrum: 0.4007709096185863
author:
  name: Jeffrey Lain
  email: sinotai@gmail.com
name: Testing Fashion Notes
navigation:
  - name: Mr Porter
    url: 'https://www.mrporter.com/en-tw/?spinlogo=1'
    type: external
  - name: Suitsupply
    url: 'http://eu.suitsupply.com/en/suits'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/18fcc66f-5648-41d0-8e56-88f16254e328.png
title: Jeffrey's Testing!
